# Generated by Django 5.2.4 on 2025-08-09 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('sender', models.EmailField(max_length=255)),
                ('recipient', models.EmailField(max_length=255)),
                ('body_plain', models.TextField(blank=True, help_text='Plain text version of the email body.')),
                ('body_html', models.TextField(blank=True, help_text='HTML version of the email body.')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('raw_payload', models.JSONField(help_text='The full, raw JSON payload from the webhook.')),
            ],
            options={
                'verbose_name': 'Received Email',
                'verbose_name_plural': 'Inbox (Received Emails)',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(help_text='Comma-separated email addresses.', max_length=500)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Draft',
                'verbose_name_plural': 'Email Drafts',
                'ordering': ['-updated_at'],
            },
        ),
    ]
