# Generated by Django 5.2.4 on 2025-08-02 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_chat_with_talents', models.BooleanField(default=False, help_text='If checked, this Talent user can initiate chat with other Talent users.')),
                ('can_upload_public_media', models.BooleanField(default=True, help_text='If checked, this user can upload public media to their profile.')),
                ('can_send_messages', models.BooleanField(default=True, help_text='If unchecked, user cannot send new messages.')),
                ('can_receive_messages', models.BooleanField(default=True, help_text='If unchecked, user cannot receive new messages.')),
                ('bio', models.TextField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
                ('user_group', models.ForeignKey(blank=True, help_text='Primary role/type of the user (e.g., Talent, Sponsor, Admin)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
            ],
        ),
    ]
