# Generated by Django 5.2.5 on 2025-08-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_profile_intro_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='A public email address for potential sponsors to contact you.', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='crypto_wallet_address',
            field=models.CharField(blank=True, help_text='Your public cryptocurrency wallet address (e.g., BTC, ETH).', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='headline',
            field=models.CharField(blank=True, help_text='A short, punchy sentence about what you do or need.', max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Link to your Instagram profile.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='languages',
            field=models.CharField(blank=True, help_text='Languages you speak, separated by commas.', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='Link to your LinkedIn profile.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='paypal_email',
            field=models.EmailField(blank=True, help_text='Your PayPal email address for direct payments (e.g., for a PayPal.me link).', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='stripe_link',
            field=models.URLField(blank=True, help_text='A direct link to a Stripe payment or product page.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Link to your Twitter profile.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='website_url',
            field=models.URLField(blank=True, help_text='Link to your personal website, portfolio, or project page.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell your story, describe your skills, or explain your project.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.CharField(default='General', help_text="Your primary category, talent, or tag (e.g., 'Music', 'Charity', 'Web Development').", max_length=100),
        ),
    ]
