# Generated by Django 5.2.5 on 2025-08-15 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_city_profile_contact_email_profile_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='crypto_wallet_address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='paypal_email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='stripe_link',
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Link to your Facebook profile.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.CharField(default='General', help_text='Your primary category, talent, or tag.', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='A public email for sponsors to contact you.', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Link to your Twitter (X) profile.'),
        ),
        migrations.CreateModel(
            name='PaymentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('PayPal', 'PayPal'), ('Payoneer', 'Payoneer'), ('Eversend', 'Eversend'), ('M-Pesa', 'M-Pesa'), ('Mobile Money', 'Mobile Money'), ('Bank Account', 'Bank Account'), ('Other', 'Other')], max_length=50)),
                ('details', models.CharField(help_text='Enter your email, phone number, account number, or a URL.', max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_links', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Comments are visible only after approval.')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='profiles.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CryptoWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_type', models.CharField(choices=[('BTC', 'Bitcoin (BTC)'), ('ETH', 'Ethereum (ETH)'), ('USDT-TRC20', 'Tether (USDT-TRC20)'), ('BNB', 'Binance Coin (BNB)'), ('SOL', 'Solana (SOL)')], max_length=50)),
                ('address', models.CharField(help_text='Enter your public wallet address.', max_length=255)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_wallets', to='profiles.profile')),
            ],
            options={
                'unique_together': {('profile', 'crypto_type')},
            },
        ),
    ]
