# Generated by Django 5.2.4 on 2025-08-05 10:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_is_admin', models.BooleanField(default=False, verbose_name='Sent by Admin')),
                ('message', models.TextField(verbose_name='Message Content')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sent At')),
                ('is_read_by_user', models.BooleanField(default=False, verbose_name='Read by User')),
                ('is_read_by_admin', models.BooleanField(default=False, verbose_name='Read by Admin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Admin Chat Message',
                'verbose_name_plural': 'Admin Chat Messages',
                'ordering': ['timestamp'],
            },
        ),
    ]
