# Generated by Django 5.2.4 on 2025-08-05 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_with_admin', '0002_customuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminchatmessage',
            name='anonymous_sender_email',
            field=models.EmailField(blank=True, help_text='Email if sender is not a registered user.', max_length=254, verbose_name='Anonymous Sender Email'),
        ),
        migrations.AddField(
            model_name='adminchatmessage',
            name='anonymous_sender_name',
            field=models.CharField(blank=True, help_text='Name if sender is not a registered user.', max_length=100, verbose_name='Anonymous Sender Name'),
        ),
        migrations.AlterField(
            model_name='adminchatmessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
