# Generated by Django 5.2.4 on 2025-08-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('ARTIST', 'Artist'), ('FOOTBALLER', 'Footballer'), ('AGENT', 'Agent'), ('SPONSOR', 'Sponsor'), ('EMERGENCY', 'Emergency'), ('EMPLOYER', 'Employer'), ('CODER', 'Coder')], default='ARTIST', max_length=20),
        ),
    ]
