# Generated by Django 5.2.4 on 2025-08-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('ARTIST', 'Artist'), ('FOOTBALLER', 'Footballer'), ('AGENT', 'Agent'), ('SPONSOR', 'Sponsor'), ('EMERGENCY', 'Emergency'), ('EMPLOYER', 'Employer'), ('CODER', 'Coder'), ('INFLUENCER', 'Influencer'), ('FILMMAKER', 'Filmmaker'), ('COMEDIAN', 'Comedian'), ('VOLLEYBALLER', 'Volleyballer'), ('VOLUNTEER', 'Volunteer'), ('JOURNALIST', 'Journalist'), ('TRADER', 'Trader'), (' BOXER', 'Boxer'), ('DONOR', 'Donor'), ('OTHER', 'Other')], default='ARTIST', max_length=20),
        ),
    ]
