# Generated by Django 5.2.4 on 2025-08-05 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sponsor',
            field=models.ForeignKey(blank=True, help_text='The user who is sponsoring, if they are logged in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsorships_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sponsor_guest_email',
            field=models.EmailField(blank=True, help_text='The email of a guest sponsor.', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sponsor_guest_name',
            field=models.CharField(blank=True, help_text='The name of a guest sponsor.', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit_crypto', 'Crypto Deposit'), ('deposit_p2p', 'P2P Deposit'), ('sponsorship_deposit', 'Sponsorship Deposit'), ('withdrawal_crypto', 'Crypto Withdrawal'), ('withdrawal_p2p', 'P2P Withdrawal'), ('internal_transfer_send', 'Internal Transfer (Sent)'), ('internal_transfer_receive', 'Internal Transfer (Received)'), ('donation', 'Donation')], max_length=50),
        ),
    ]
