# Generated by Django 5.2.4 on 2025-08-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_transaction_sponsor_transaction_sponsor_guest_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit_crypto', 'Crypto Deposit'), ('deposit_p2p', 'P2P Deposit'), ('sponsorship_deposit', 'Sponsorship Deposit (Manual)'), ('sponsorship_crypto', 'Sponsorship Deposit (Crypto)'), ('withdrawal_crypto', 'Crypto Withdrawal'), ('withdrawal_p2p', 'P2P Withdrawal'), ('internal_transfer_send', 'Internal Transfer (Sent)'), ('internal_transfer_receive', 'Internal Transfer (Received)'), ('donation', 'Donation')], max_length=50),
        ),
    ]
