# Generated by Django 5.2.4 on 2025-08-07 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0003_alter_emergencycampaign_options_and_more'),
        ('wallet', '0003_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='emergencies.emergencycampaign'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit_crypto', 'Crypto Deposit'), ('deposit_p2p', 'P2P Deposit'), ('sponsorship_deposit', 'Sponsorship Deposit (Manual)'), ('sponsorship_crypto', 'Sponsorship Deposit (Crypto)'), ('emergency_donation_crypto', 'Emergency Donation (Crypto)'), ('withdrawal_crypto', 'Crypto Withdrawal'), ('withdrawal_p2p', 'P2P Withdrawal'), ('internal_transfer_send', 'Internal Transfer (Sent)'), ('internal_transfer_receive', 'Internal Transfer (Received)')], max_length=50),
        ),
    ]
