# Generated by Django 5.2.4 on 2025-08-06 18:52

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the emergency campaign.', max_length=255)),
                ('description', models.TextField(help_text='A detailed description of the cause.')),
                ('goal_amount', models.DecimalField(decimal_places=2, help_text='The target fundraising amount.', max_digits=12)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='The total amount raised from *approved* donations.', max_digits=12)),
                ('main_image', cloudinary.models.CloudinaryField(blank=True, help_text='The main promotional image for the campaign.', max_length=255, null=True, verbose_name='image')),
                ('video_url', models.URLField(blank=True, help_text='Optional: A link to a promotional video (e.g., YouTube, Vimeo).', null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(help_text='The date when the campaign will officially end.')),
                ('is_active', models.BooleanField(default=False, help_text='This is automatically set to True when a campaign is approved by an admin.')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', help_text='The current status of the campaign.', max_length=20)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_request_campaign', 'Can request an emergency campaign')],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('pending_approval', 'Pending Approval'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending_payment', max_length=20)),
                ('payment_method', models.CharField(choices=[('wallet', 'Wallet'), ('crypto', 'Cryptocurrency'), ('other', 'Other')], max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='Transaction ID from the payment system (e.g., NOWPayments ID).', max_length=100, null=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations_made', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='emergencies.emergencycampaign')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CampaignImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(help_text='Upload an image for the campaign gallery.', max_length=255, verbose_name='image')),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the image.', max_length=255)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='emergencies.emergencycampaign')),
            ],
        ),
    ]
