# Generated by Django 5.2.4 on 2025-08-07 15:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0002_alter_donation_donor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergencycampaign',
            options={'ordering': ['-start_date'], 'permissions': [('can_request_campaign', 'Can request an emergency campaign')]},
        ),
        migrations.AlterField(
            model_name='emergencycampaign',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='The total amount raised from *completed* donations.', max_digits=12),
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
