# Generated by Django 5.2.5 on 2025-08-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0005_emergencycampaign_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycampaign',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Check this box to feature the campaign on the homepage.'),
        ),
    ]
