# Generated by Django 5.2.4 on 2025-08-08 05:24

import ckeditor_uploader.fields
import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('subtitle', models.CharField(blank=True, max_length=250, null=True)),
                ('slug', models.SlugField(blank=True, max_length=250, unique_for_date='published_at')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(help_text='Main content of the post. You can upload images directly.')),
                ('featured_image', cloudinary.models.CloudinaryField(blank=True, help_text='A primary image for the post.', max_length=255, null=True, verbose_name='image')),
                ('featured_video', cloudinary.models.CloudinaryField(blank=True, help_text='A primary video for the post.', max_length=255, null=True, verbose_name='video')),
                ('attachment', cloudinary.models.CloudinaryField(blank=True, help_text='Attach a PDF or other document.', max_length=255, null=True, verbose_name='attachment')),
                ('title_color', models.CharField(default='#000000', help_text='Hex color code for the title (e.g., #FF5733).', max_length=7)),
                ('font_size', models.PositiveIntegerField(default=32, help_text='Font size for the title in pixels.')),
                ('underline_title', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, help_text='You can set a future date to schedule the post.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='updates.category')),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['-published_at'], name='updates_pos_publish_115855_idx')],
            },
        ),
    ]
